python framework/train_simplified.py \
    --config simplified \
    --data_root /user_data/yingjueb/ecog_pretrain/preprocessed \
    --mvpformer_checkpoint mvpformer/ckpts/genie-m-base.pt \
    --output_dir outputs/simplified_persub_gpt2 \
    --alignment_weight 0.5 \
    --temporal_weight 0.5 \
    --num_epochs 50 \
    --batch_size 64 \
    --learning_rate 1e-4 \
    --per_subject \